#!/usr/bin/env python3
"""
scripts/scaffold_project.py

Instant project scaffolding utility for the `devs` system.

Creates a new, agent-friendly, devs-ready project structure
per TAS-040 and TAS-104 specifications.

Requirement: [1_PRD-REQ-NEED-MAKER-01]

Usage:
    python3 scripts/scaffold_project.py init-project <path>
    python3 scripts/scaffold_project.py init-project ./my-new-project
    python3 scripts/scaffold_project.py init-project /absolute/path/my-project
"""

import argparse
import json
import sys
import uuid
from pathlib import Path

# ── Template Content ──────────────────────────────────────────────────────────

_GITIGNORE = """\
# Node
node_modules/
dist/
build/
.cache/

# Environment
.env
.env.local
.env.*.local

# Logs
*.log
logs/

# OS
.DS_Store
Thumbs.db

# IDE
.idea/
*.swp
*.swo
"""

_DEVS_GITIGNORE = """\
# Runtime state — do not commit to VCS
state.sqlite
*.sqlite
*.db
memory.lancedb/
trace.log
snapshots/
"""

_DEVS_POLICY = """\
# .devs/ Access Policy

## Overview

This directory is the **Flight Recorder** — the internal orchestrator state
store for this `devs`-managed project.

## Developer Agent Write-Access Prohibition

**Developer Agents have NO write access to this directory.**

Only the following components may read or write `.devs/`:

- `@devs/core` (state management)
- `@devs/memory` (vector database)
- The orchestrator process itself

Modifying `.devs/` directly will corrupt the project state and may cause
loss of progress.

## Contents

| File/Directory      | Purpose                                                             |
|---------------------|---------------------------------------------------------------------|
| `state.sqlite`      | Primary ACID-compliant relational store (agent logs, tasks, reqs)  |
| `memory.lancedb/`   | Vector database: semantic embeddings of architectural decisions     |
| `trace.log`         | Append-only log of all agent-to-agent communication and tool output |
| `snapshots/`        | Filesystem diffs for "Project Rewind" (restore to any Task ID)     |
| `config.json`       | Orchestrator settings: model tiers, token budgets, active plugins   |
"""

_ENV_EXAMPLE = """\
# Environment Template — copy to .env and fill in real values.
# NEVER commit .env to version control.

# Application
NODE_ENV=development

# Add project-specific environment variables below:
"""

_README = """\
# {project_name}

> Generated by [devs](https://github.com/mrwilson/devs) — an agentic AI system
> that creates complete, tested greenfield software projects.

## Overview

This project was scaffolded with the `devs` scaffolding utility and is
immediately **devs-ready** — fully configured for agentic AI development
and Glass-Box observability.

## Quick Start

```bash
# Install dependencies
pnpm install

# Run tests
pnpm test

# Build
pnpm build
```

## Project Structure

```
{project_name}/
├── .devs/           # Internal Orchestrator State (Flight Recorder)
├── .agent/          # Agent-Oriented Documentation (AOD)
├── mcp-server/      # Project-Specific MCP Observability Server
├── src/             # Application Source Code
├── tests/           # Red-Green-Refactor Test Suite
├── docs/            # High-Level Specs & Research Reports
├── scripts/         # Utility & Automation Scripts
└── .github/         # CI/CD & Workflow Definitions
```

## Agent-Oriented Documentation

See [.agent/index.agent.md](.agent/index.agent.md) for the AI agent entry
point and architectural guidance.
"""

_AGENT_INDEX = """\
# Agent Entry Point: {project_name}

> **For AI Agents**: This is your entry point. Read this before touching any code.

## Core Philosophy

This project is built for **Glass-Box transparency** — every module has
explicit documentation for AI agents, agentic hooks for debugging, and
clear separation of concerns.

## High-Level Architecture

*[To be filled in during the research/specification phase]*

## The Rules of the House

- All business logic lives in `src/`
- All test files mirror the `src/` structure under `tests/`
- Agent-oriented documentation lives in `.agent/modules/<module-name>.agent.md`
- NEVER manually modify `.devs/` — it is the orchestrator's state store

## Module Catalog

See [catalog.json](catalog.json) for the machine-readable module map.

## Agentic Hooks

*[To be populated by the MCP server implementation in `mcp-server/`]*
"""

_TESTS_README = """\
# Tests

This directory follows the Red-Green-Refactor TDD pattern.

## Structure

```
tests/
├── unit/         # Atomic logic tests
├── integration/  # Cross-module flow tests
├── e2e/          # Full user-journey validation
└── agent/        # Agentic observability tests (run by Reviewer Agent)
```
"""

_DOCS_README = """\
# Documentation

High-level specifications and research reports generated by `devs`.

## Structure

```
docs/
├── research/   # Market, competitive, tech, and user research reports
└── specs/      # PRD, TAS, MCP Design, UI/UX, Security specifications
```
"""

_SCRIPTS_README = """\
# Scripts

Utility and automation scripts for this project.

## Standard Scripts

| Script                 | Purpose                                                      |
|------------------------|--------------------------------------------------------------|
| `bootstrap-sandbox.sh` | Prepare the Docker/WebContainer sandbox environment          |
| `run-mcp.sh`           | Start the project's internal MCP observability server        |
| `validate-all.sh`      | Run the full verification suite (Lint, Build, Test)          |
"""

_SRC_GITKEEP = "# Application source code will be placed here\n"


# ── Core scaffolding logic ────────────────────────────────────────────────────

def _package_json(project_name: str, project_id: str) -> dict:
    """Build a template package.json with the required devs metadata (TAS-076)."""
    return {
        "name": project_name,
        "version": "0.0.1",
        "private": True,
        "description": f"{project_name} — generated by devs",
        "devs": {
            "project_id": project_id,
            "version": "1.0.0",
            "generated_by": "devs-scaffold",
        },
        "engines": {
            "node": ">=22",
            "pnpm": ">=9",
        },
        "scripts": {
            "build": "echo 'build: configure for your chosen toolchain'",
            "test": "echo 'test: configure for your chosen test runner'",
            "lint": "echo 'lint: configure for your chosen linter'",
            "fmt": "echo 'fmt: configure for your chosen formatter'",
        },
    }


def scaffold_project(project_path: str) -> int:
    """
    Create a new devs-ready project at the specified path.

    Directory layout (TAS-040, TAS-104):
        <project-root>/
        ├── .devs/          # Flight Recorder (TAS-061)
        ├── .agent/         # Agent-Oriented Documentation (TAS-042)
        ├── mcp-server/     # MCP Observability Server (TAS-062)
        ├── src/            # Application Source Code
        ├── tests/          # Test Suite (unit, integration, e2e, agent)
        ├── docs/           # Specs & Research Reports (TAS-044)
        ├── scripts/        # Utility & Automation Scripts
        ├── .github/        # CI/CD Workflow Definitions
        ├── .gitignore
        ├── .env.example
        ├── README.md
        └── package.json    # Includes devs metadata (TAS-076)

    Returns 0 on success, 1 on failure.
    """
    root = Path(project_path).resolve()
    project_name = root.name
    project_id = str(uuid.uuid4())

    print(f"Scaffolding devs project: {project_name}")
    print(f"  Path:       {root}")
    print(f"  Project ID: {project_id}")
    print()

    # ── Directories (TAS-104) ──────────────────────────────────────────────
    directories = [
        ".devs",
        ".agent",
        ".agent/modules",
        "mcp-server",
        "mcp-server/src",
        "mcp-server/src/tools",
        "mcp-server/src/resources",
        "mcp-server/src/prompts",
        "src",
        "tests",
        "tests/unit",
        "tests/integration",
        "tests/e2e",
        "tests/agent",
        "docs",
        "docs/research",
        "docs/specs",
        "scripts",
        ".github",
        ".github/workflows",
    ]

    for rel in directories:
        (root / rel).mkdir(parents=True, exist_ok=True)
        print(f"  [mkdir] {rel}/")

    print()

    def write(rel: str, content: str) -> None:
        (root / rel).write_text(content, encoding="utf-8")
        print(f"  [write] {rel}")

    # ── Root-level files ───────────────────────────────────────────────────
    write(".gitignore", _GITIGNORE)
    write(".env.example", _ENV_EXAMPLE)
    write("README.md", _README.format(project_name=project_name))
    write(
        "package.json",
        json.dumps(_package_json(project_name, project_id), indent=2) + "\n",
    )

    # ── .devs/ — Flight Recorder (TAS-061) ────────────────────────────────
    write(".devs/.gitignore", _DEVS_GITIGNORE)
    write(".devs/POLICY.md", _DEVS_POLICY)

    # ── .agent/ — Agent-Oriented Documentation (TAS-042) ──────────────────
    write(".agent/index.agent.md", _AGENT_INDEX.format(project_name=project_name))
    catalog = {
        "version": "1.0.0",
        "project": project_name,
        "modules": [],
        "generated_by": "devs-scaffold",
    }
    write(".agent/catalog.json", json.dumps(catalog, indent=2) + "\n")

    # ── Scaffold-only placeholder files (git tracks empty dirs) ───────────
    # Empty leaf directories must have a .gitkeep so git preserves them.
    write("src/.gitkeep", _SRC_GITKEEP)
    write(".agent/modules/.gitkeep", "")
    write("mcp-server/src/tools/.gitkeep", "")
    write("mcp-server/src/resources/.gitkeep", "")
    write("mcp-server/src/prompts/.gitkeep", "")
    write("tests/README.md", _TESTS_README)
    write("tests/unit/.gitkeep", "")
    write("tests/integration/.gitkeep", "")
    write("tests/e2e/.gitkeep", "")
    write("tests/agent/.gitkeep", "")
    write("docs/README.md", _DOCS_README)
    write("docs/research/.gitkeep", "")
    write("docs/specs/.gitkeep", "")
    write("scripts/README.md", _SCRIPTS_README)
    write(".github/workflows/.gitkeep", "")

    print()
    print(f"Project '{project_name}' scaffolded successfully.")
    print()
    print("Next steps:")
    print(f"  1. cd {root}")
    print("  2. Configure package.json scripts for your chosen toolchain")
    print("  3. Review .agent/index.agent.md and update with project details")
    print("  4. git init && git add . && git commit -m 'Initial scaffold'")
    return 0


# ── CLI ───────────────────────────────────────────────────────────────────────

def _cmd_init_project(args: argparse.Namespace) -> int:
    root = Path(args.path).resolve()

    if root.is_file():
        print(
            f"Error: target path '{args.path}' already exists as a file.",
            file=sys.stderr,
        )
        return 1

    if root.is_dir() and any(root.iterdir()):
        print(
            f"Error: target directory '{args.path}' already exists and is not empty.",
            file=sys.stderr,
        )
        print("Use a new path or an empty directory.", file=sys.stderr)
        return 1

    return scaffold_project(str(root))


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="scaffold_project.py",
        description=(
            "devs scaffolding utility — create agent-friendly, devs-ready projects "
            "per TAS-040 and TAS-104 specifications."
        ),
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser(
        "init-project",
        help="Scaffold a new devs-ready project at the given path",
    )
    init_parser.add_argument(
        "path",
        help="Destination path for the new project (e.g. ./my-project)",
    )

    args = parser.parse_args()

    if args.command == "init-project":
        return _cmd_init_project(args)

    print(f"Unknown command: {args.command}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
